export const FETCH_TOP_STORIESID = "FETCH_TOP_STORIESID";
export const FETCH_NEW_STORIESID = "FETCH_NEW_STORIESID";
export const FETCH_TOP_STORIES = "FETCH_TOP_STORIES";
export const FETCH_NEW_STORIES = "FETCH_NEW_STORIES";
export const FAILURE = "FAILURE";
